:py:mod:`relevanceai.errors`
============================

.. py:module:: relevanceai.errors

.. autoapi-nested-parse::

   Missing field error



Module Contents
---------------

.. py:exception:: RelevanceAIError



   Base class for all errors


.. py:exception:: MissingFieldError



   Error handling for missing fields


.. py:exception:: APIError



   Error related to API


.. py:exception:: ClusteringResultsAlreadyExistsError(field_name, message='Clustering results for %s already exist')



   Exception raised for existing clustering results

   .. attribute:: message -- explanation of the error

      


